<?xml version="1.0" encoding="utf-8" ?>
<Project>
	<!-- Copy to Plugins -->
	<Target Name="CopyToPlugins" AfterTargets="Build" Condition="'$(CI)'!='TRUE' and '$(PluginsPath)'!='' and Exists('$(PluginsPath)') and '$(Configuration)'!='Legal' and '$(Configuration)'!='LegalDebug'">
		<ItemGroup>
			<FilesToCopy Include="$(TargetPath)" />
			<FilesToCopy Include="$(TargetDir)$(TargetName).pdb" Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
		</ItemGroup>
		<Copy SourceFiles="@(FilesToCopy)" DestinationFiles="@(FilesToCopy->'$(PluginsPath)\%(Filename)%(Extension)')" />
		<Message Text="Copied $(TargetFileName) to Plugins" Importance="high"/>
	</Target>

	<!-- Build the Legal variant after Debug/Release builds -->
	<Target Name="BuildLegalAndLegalDebug" AfterTargets="Build" Condition="'$(Configuration)'=='Debug' or '$(Configuration)'=='Release'">
		<MSBuild Projects="$(MSBuildProjectFile)" Properties="Configuration=Legal" />
		<MSBuild Projects="$(MSBuildProjectFile)" Properties="Configuration=LegalDebug" />
	</Target>
</Project>